FULL_LEAK = "full_leak"
PARTIAL_LEAK = "partial_leak"
ENCODING_LEAK = "encoding_leak"
RECONSTRUCTION_LEAK = "reconstruction_leak"
TRANSLATION_LEAK = "translation_leak"
SEMANTIC_LEAK = "semantic_leak"
NO_LEAK = "no_leak"

SEVERITY_NONE = "none"
SEVERITY_LOW = "low"
SEVERITY_MEDIUM = "medium"
SEVERITY_HIGH = "high"
SEVERITY_CRITICAL = "critical"

SEVERITY_ORDER = {
    SEVERITY_NONE: 0,
    SEVERITY_LOW: 1,
    SEVERITY_MEDIUM: 2,
    SEVERITY_HIGH: 3,
    SEVERITY_CRITICAL: 4,
}

LEAK_SEVERITY_MAP = {
    FULL_LEAK: SEVERITY_CRITICAL,
    ENCODING_LEAK: SEVERITY_CRITICAL,
    RECONSTRUCTION_LEAK: SEVERITY_HIGH,
    PARTIAL_LEAK: SEVERITY_HIGH,
    TRANSLATION_LEAK: SEVERITY_HIGH,
    SEMANTIC_LEAK: SEVERITY_MEDIUM,
    NO_LEAK: SEVERITY_NONE,
}

LEAK_ACTION_MAP = {
    FULL_LEAK: "block",
    ENCODING_LEAK: "block",
    RECONSTRUCTION_LEAK: "block",
    PARTIAL_LEAK: "redact",
    TRANSLATION_LEAK: "redact",
    SEMANTIC_LEAK: "redact",
    NO_LEAK: "allow",
}
