NO_ASSET_REFERENCE = "no_asset_reference"
ASSET_TYPE_MENTION = "asset_type_mention"
ASSET_VALUE_REFERENCE = "asset_value_reference"
ASSET_ALIAS_REFERENCE = "asset_alias_reference"
PROTECTED_REGISTRY_MATCH = "protected_registry_match"


class AssetReference:
    NO_ASSET_REFERENCE = "no_asset_reference"
    ASSET_TYPE_MENTION = "asset_type_mention"
    ASSET_VALUE_REFERENCE = "asset_value_reference"
    ASSET_ALIAS_REFERENCE = "asset_alias_reference"
    PROTECTED_REGISTRY_MATCH = "protected_registry_match"


class Operation:
    EXPLAIN = "EXPLAIN"
    COMPARE = "COMPARE"
    HOW_TO = "HOW_TO"
    GENERATE_EXAMPLE = "GENERATE_EXAMPLE"
    DISCLOSE = "DISCLOSE"
    EXTRACT = "EXTRACT"
    RECONSTRUCT = "RECONSTRUCT"
    TRANSFORM = "TRANSFORM"
    BYPASS = "BYPASS"
    AUTHORIZE_CLAIM = "AUTHORIZE_CLAIM"
    UNKNOWN = "UNKNOWN"


class Scope:
    GENERAL_CONCEPT = "GENERAL_CONCEPT"
    EXAMPLE_PLACEHOLDER = "EXAMPLE_PLACEHOLDER"
    USER_PROVIDED_TEXT = "USER_PROVIDED_TEXT"
    CURRENT_SYSTEM = "CURRENT_SYSTEM"
    HIDDEN_CONTEXT = "HIDDEN_CONTEXT"
    PROTECTED_REGISTRY = "PROTECTED_REGISTRY"
    SESSION_HISTORY = "SESSION_HISTORY"
    UNKNOWN_INTERNAL = "UNKNOWN_INTERNAL"
    UNKNOWN = "UNKNOWN"


class DisclosureMode:
    NONE = "NONE"
    FULL_VALUE = "FULL_VALUE"
    PARTIAL_VALUE = "PARTIAL_VALUE"
    PREFIX_SUFFIX = "PREFIX_SUFFIX"
    LENGTH_ONLY = "LENGTH_ONLY"
    CHAR_INDEX = "CHAR_INDEX"
    ENCODED_VALUE = "ENCODED_VALUE"
    TRANSLATED_VALUE = "TRANSLATED_VALUE"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    RECONSTRUCTED_VALUE = "RECONSTRUCTED_VALUE"
