NO_LEAK = "NO_LEAK"
LOW_RISK_HINT = "LOW_RISK_HINT"
PARTIAL_LEAK = "PARTIAL_LEAK"
FULL_LEAK = "FULL_LEAK"
CRITICAL_LEAK = "CRITICAL_LEAK"

ALLOW = "ALLOW"
REDACT = "REDACT"
BLOCK = "BLOCK"
REWRITE = "REWRITE"
ESCALATE = "ESCALATE"

SEVERITY_ACTION_MAP = {
    NO_LEAK: ALLOW,
    LOW_RISK_HINT: ALLOW,
    PARTIAL_LEAK: REDACT,
    FULL_LEAK: REDACT,
    CRITICAL_LEAK: BLOCK,
}

SEVERITY_ORDER = {
    NO_LEAK: 0,
    LOW_RISK_HINT: 1,
    PARTIAL_LEAK: 2,
    FULL_LEAK: 3,
    CRITICAL_LEAK: 4,
}
